on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: test-coverage

jobs:
  test-coverage:

    concurrency:
      group: gpu-tests
    runs-on:
      - "runs-on=${{ github.run_id }}/family=g4dn.xlarge/image=ubuntu24-gpu-x64/spot=true"

    container:
      image: nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04
      options: --gpus all

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TORCH_INSTALL: 1
      TORCH_TEST: 1
      DEBIAN_FRONTEND: 'noninteractive'

    steps:
      - uses: actions/checkout@v4

      - run: |
          apt-get update -y
          apt-get install -y sudo software-properties-common dialog apt-utils tzdata protobuf-compiler libprotobuf-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: false
          extra-packages: any::rcmdcheck
          needs: check

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
